from Bio.pairwise2 import format_alignment
from Bio import pairwise2
import string
#alignments = pairwise2.align.globalxx('ACCGTACCGTACCGT', 'ACC')
'''for a in pairwise2.align.globalms('UNSPVIQIICIIRZIIPMQIYIRZSIOIDPLLIIQIIRZIIGEPAQIIIGIIQRPITIIQRPSIRIUGQIKXIJIKXIRPFIQIRPL', 'HWBIXUNSPIIQRZIJIPIIGEPIIJIPIICICICIPIIPIIPFGXIIIXPaYIPFGXIIIIXPaYIPSIIIQIIQRRPSIQIIQRRIQICIRPbFGXIIIIIInXPFGXIIIInXPaYIPFEPL', 2, -1, -1, -1):
	print(format_alignment(*a))
'''

def Convert2(string):
    list1=[]
    list1[:0]=string
    return list1

def cambio(a,elemento,canje):
  return [canje if x==elemento else x for x in a]
  #return [canje if x==elemento else x for x in a]
#cambio(a,'#','A')

canjes=Convert2(string.ascii_uppercase+string.ascii_lowercase)
a=['NUMERAL','INCLUDE','MENORQUE','IDENTIFICADOR','MAYORQUE','USING','NAMESPACE','STD','PUNTOCOMA','IDENTIFICADOR','IDENTIFICADOR','PARIZQ','PARDER','#','LLAIZQ','IDENTIFICADOR','MULT','IDENTIFICADOR','PUNTOCOMA','IDENTIFICADOR','IDENTIFICADOR','ASIGNAR','ENTERO','PUNTOCOMA','IDENTIFICADOR','IDENTIFICADOR','MULT','IDENTIFICADOR','PUNTOCOMA','IDENTIFICADOR','IDENTIFICADOR','COMA','IDENTIFICADOR','COMA','IDENTIFICADOR','COMA','IDENTIFICADOR','PUNTOCOMA','IDENTIFICADOR','IDENTIFICADOR','PUNTOCOMA','IDENTIFICADOR','IDENTIFICADOR','PUNTOCOMA','COUT','MAYORDER','COMDOB','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','COMDOB','PUNTOCOMA','CIN','MAYORIZQ','IDENTIFICADOR','PUNTOCOMA','COUT','MAYORDER','COMDOB','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','COMDOB','PUNTOCOMA','CIN','MAYORIZQ','IDENTIFICADOR','PUNTOCOMA','SI','IDENTIFICADOR','IDENTIFICADOR','PARIZQ','IDENTIFICADOR','IDENTIFICADOR','PARIZQ','PARDER','PARDER','PUNTOCOMA','SI','PARIZQ','IDENTIFICADOR','IDENTIFICADOR','PARIZQ','PARDER','PARDER','IDENTIFICADOR','PARIZQ','IDENTIFICADOR','COMA','IDENTIFICADOR','PARDER','PUNTOCOMA','SINO','COUT','MAYORDER','COMDOB','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','NOT','COMDOB','PUNTOCOMA','COUT','MAYORDER','COMDOB','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','IDENTIFICADOR','NOT','COMDOB','PUNTOCOMA','CIN','MAYORIZQ','IDENTIFICADOR','PUNTOCOMA','RETURN','ENTERO','PUNTOCOMA','LLADER']
init=0
for i in range(init,len(a)):
	#for j in range(0,len(a)):
	if (len(a[i])>1):
		a=cambio(a,a[i],canjes[init])
		init=init+1

print(a,'\n')


print(a.index('#'))

#print (Convert2(string.ascii_lowercase+string.ascii_uppercase))
#print (Convert2(string.ascii_uppercase))


'''
i=0
while i<len(canjes):
    a=cambio(a,a[i],canjes[i])
    i=i+1
print(a)
'''

#print(25.*100/len('HWBIXUNSPIIQRZIJIPIIGEPIIJIPIICICICIPIIPIIPFGXIIIXPaYIPFGXIIIIXPaYIPSIIIQIIQRRPSIQIIQRRIQICIRPbFGXIIIIIInXPFGXIIIInXPaYIPFEPL'))